# Assignment 1
*Topics: matrix operations, gaussian elimination, solving a system, LU decomposition*

For details on how to upload your notebook back to canvas, check the canvas homepage for a quick tutorial. For additional help with the jupyter workflow and python in general, attend an office hour at 6pm PST on Wednesday. 

In [38]:
import numpy as np
import scipy.linalg as la


**Exercise 1**
Each part of Exercise 1 is a True/False question. 

**Exercise 1(a)**
Let $A$ be a $m$ by $n$ matrix such that $m>n$ and rank$(A) = n$. There is a unique solution of $Ax = b$ for any $b$.

Assign the variable ONEA the value True if the above statement is true and False if it is not. 

For example, write ONEA = True (note the capitalization)


In [39]:
# YOUR CODE HERE
ONEA = False

In [40]:
assert isinstance(ONEA,bool), "Assign the variable True or False"
print("Checkpoint 1.1 passed")

Checkpoint 1.1 passed


**Exercise 1(b)**

If $P$ is a permutation matrix such that $PA$ interchanges 2 rows of $A$, then $P^2 = I$.

Assign the variable ONEB the value True if the above statement is true and False if it is not. 





In [41]:
# YOUR CODE HERE
ONEB = True

**Exercise 1(c)**

If $x$ is a $n$-dim vector with real entries such that $\| x \|_1 = \| x \|_\infty = \lambda$ then $\| x \|_p = \lambda$ for any $p>1$.

Assign the variable ONEC the value True if the above statement is true and False if it is not. 



In [42]:
# YOUR CODE HERE
ONEC = True

**Exercise 1(d)**

If $\|A \| = 1$ then $A = I$. 

Assign the variable ONED the value True if the above statement is true and False if it is not. 



In [43]:
# YOUR CODE HERE
ONED = False

**Exercise 1(e)**

Define $\|x\|_{\text{min}} = \min_k|x_k|$ for any $n$-dim real vector $x$. Then $\|x\|_{\text{min}}$ is a norm. 

Assign the variable ONEE the value True if the above statement is true and False if it is not. 



In [44]:
# YOUR CODE HERE
ONEE = False

**Exercise 2**

Find a value of $c$ such that the system $Ax = b$ has infinitely many solutions where 

$$ A = \begin{pmatrix} 3 & -1 & 2 \\ 1 & 1 & -1 \\ 2 & -2 & 3 \end{pmatrix} \qquad b = \begin{pmatrix} 3 \\ 2 \\ c \end{pmatrix}. $$


Record your answer by assigning the variable VALC the value of c. 


In [45]:
# YOUR CODE HERE
# Row 3 = row 1 - row 2 so I can do 3-2 yields c = 1 to get row 3 is a linear combination of rows 1 and 2
VALC = 1

**Exercise 3(a)**

Recall that in numpy, we create matrices by calling np.array. Assign variable $A$ to the matrix
$$\begin{pmatrix} 1 & 3 & 6 \\ 10 & 15 & 21 \\ 28 & 36 & 45 \end{pmatrix}$$
and assign $B$ to the matrix 
$$ \begin{pmatrix} 1 & 4 & 9 \\ 16 & 25 & 36 \\ 49 & 64 & 81 \end{pmatrix}$$.

In [46]:
# YOUR CODE HERE
A = np.array([[1,3,6],[10,15,21],[28,36,45]])
B = np.array([[1,4,9],[16,25,36],[49,64,81]])

In [47]:
assert isinstance(A,np.ndarray), "Make A an array"
print("Checkpoint 1.1 passed")

assert isinstance(B,np.ndarray), "Make B an array"
print("Checkpoint 1.2 passed")

assert np.allclose(A,np.array([[1,3,6],[10,15,21],[28,36,45]])), "Make A has the right values."
print("Checkpoint 1.3 passed")

assert np.allclose(B,np.array([[1,4,9],[16,25,36],[49,64,81]])), "Make B has the right values."
print("Checkpoint 1.4 passed")

Checkpoint 1.1 passed
Checkpoint 1.2 passed
Checkpoint 1.3 passed
Checkpoint 1.4 passed


**Exercise 3(b)**
Assign the variable DETAB the value of the determinant of matrix $AB$. 

In [48]:
# YOUR CODE HERE
DETAB = np.linalg.det(np.matmul(A, B))

In [49]:
print(DETAB)

5832.000000003545


In [50]:
assert DETAB>3000, "Check that you did the correct matrix multiplication."
print("Checkpoint 1.5 passed")

Checkpoint 1.5 passed


In [51]:
assert np.isclose(DETAB,5831.999999999371), "In np, matrix multiplication is done with an @"
print("Checkpoint 1.6 passed")

Checkpoint 1.6 passed


**Exercise 3(c)**

Assign the variable $C$ the matrix

$$\begin{pmatrix} 1 & 2 & 3 & 4 \\ 5 & 6 & 7 & 8 \\ 9 & 10 & 11 & 12 \\ 13 & 14 & 15 & 16 \end{pmatrix}$$.



In [52]:
# YOUR CODE HERE
C = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [53]:
assert np.allclose(C,np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])), "Check your entries."
print("Checkpoint 1.7 passed")

Checkpoint 1.7 passed


**Exercise 3(d)**
Assign the variable CRANK the value of the rank of matrix C. 

In [54]:
# YOUR CODE HERE
CRANK = np.linalg.matrix_rank(C)

**Exercise 3(e)**

Let $D = AB$. Let $C_1$ be the first column of $D$ and $R_3$ be the third row of $D$.
Assign variable $T$ the integer value $R_3C_1$. 

Hint: If D is an numpy array, use D[i] to return a matrix's $i^{th}$ row, D[: , j] to return a matrix's $j^{th}$ column, and np.dot to compute a dot product. 

In [55]:
# YOUR CODE HERE
D = np.matmul(A, B)
T = np.dot(D[2], D[:, 0])

**Exercise 4**

Let $A,B$ be the matrices of Exercise 3. Let 

$$ b = \begin{pmatrix} 1 \\ 1 \\ 1 \end{pmatrix} \qquad c = \begin{pmatrix} \sqrt{2} \\ \sqrt{3} \\ \sqrt{5} \end{pmatrix} . $$


Make the following variable assignments for variables $w,x,y,z$. 


(i) $w$ the solution to $Aw = b$
(ii) $x$ the solution to $Bx = b$
(iii) $y$ the solution to $Ay = c$, 
(iv) $z$ the solution to $Bz = c$. 

To find the solution to a matrix equation $Ax = b$, use np.linalg.solve(A,b).

In [56]:
# YOUR CODE HERE
b = np.array([[1], [1], [1]])
c = np.array([[2**0.5], [3**0.5], [5**0.5]])
w = np.linalg.solve(A, b)
x = np.linalg.solve(B, b)
y = np.linalg.solve(A, c)
z = np.linalg.solve(B, c)

In [57]:
assert np.allclose(w,np.linalg.solve(A,b)), "Use np.linalg.solve(A,b)"
print("Checkpoint 2.1 passed")



Checkpoint 2.1 passed


**Exercise 5** 

To find the LU decomposition of a matrix $M$, we use the function call la.lu(M). This will return three matrices (arrays), a permutation array $P$, a lower triangular matrix $L$, and an upper triangular matrix $U$ such that 
$$ M = PLU. $$
To compute the LU decomposition of a matrix $M$, we simply can run the code: P,L,U = la.lu(M). This will assign the variables P,L,U the values described above. 

Note that in class, we considered matrices that can be reduced to row echelon form without partial pivoting (i.e., without swapping rows). In that case, the matrix $P$ above ends up being the identity matrix. In the more general case where we have to swap rows, we need a non-trivial [permutation matrix](https://en.wikipedia.org/wiki/Permutation_matrix). 

Find the LU decomposition of the matrix $C$ as in Exercise 3. Precisely, assign variables P,L,U the matrix values such that $PC = LU$. Be careful: the $P$ in $PC = LU$ is is still a permutation matrix, but it is not the same as the P returned by la.lu.


In [61]:
# YOUR CODE HERE
P, L, U = la.lu(C)

print(np.matmul(L, U))
P = np.array([[0, 0, 0, 1], [1, 0, 0, 0], [0, 0, 1, 0], [0, 1, 0, 0]])
print(np.matmul(P,C))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[13. 14. 15. 16.]
 [ 1.  2.  3.  4.]
 [ 9. 10. 11. 12.]
 [ 5.  6.  7.  8.]]


In [59]:
assert isinstance(P,np.ndarray), "Check your function calls."
assert isinstance(L,np.ndarray), "Check your function calls."
assert isinstance(U,np.ndarray), "Check your function calls."
print("Checkpoint 3.1 passed")

Checkpoint 3.1 passed


In [60]:
assert P.shape == (4,4)
assert L.shape == (4,4) 
assert U.shape == (4,4)
print("Checkpoint 3.2 passed")

Checkpoint 3.2 passed
